### ISSUE TITLE
Support "on failure only" post action

### ISSUE THREAD

**Issue by noirbizarre** [gacts/run-and-post-run#37]
Hi 👋🏼 

Thanks for this action which is solving a real lack in GitHub Actions.

I would like to suggest an improvement that would match a recurring use case I have in my actions: clean up on failure.
To do so, it would be great to have a `on-failure` boolean input (with default `false`) that would enable the post action to run only if the job failed.

It would result into something very clean:

```yaml
- name: my step with cleanable side-effect
  uses: gacts/run-and-post-run@v1
  with: 
    run: do-something-needing-cleanup-on-failure
    post: cleanup
    on-failure: true
```
Does it seem acceptable to you ?
Are you willing to implement this or accept a pull-request implementing this ?

Thanks by advance for your time !

**Comment by jetexe** [comment]
Hi! Thanks for your issue and worm words for this action!

The job.status context variable can be used within your scripts to dynamically determine the current state of a job. This enables you to implement conditional actions based on the job's outcome.

```yml
- name: my step with cleanable side-effect
  uses: gacts/run-and-post-run@v1
  with:
    run: do-something-needing-cleanup-on-failure
    post: if [ "${{ job.status }}" = "failure" ]; then cleanup; fi
```

I added an example in #38 

To conditionally execute actions based on multiple job states (e.g., failure and cancelled), consider using a bitmask approach. Here's an example:.: 

```yml
post-state-condition: "ON_FAILURE|ON_CANCELLED" 
```

While this approach offers a bit flexibility, it may introduce additional complexity to the action API and code implementation.

I need to think more about that

**Comment by tarampampam** [comment]
@jetext I believe @noirbizarre is suggesting adding more convenient input parameters, like this:

```yaml
- name: my step with cleanable side-effect
  uses: gacts/run-and-post-run@v1
  with: 
    run: do-something-needing-cleanup-on-failure
    post: cleanup
    run-post-on-failure-only: true # when run fails, on-failure doesn't specify 
                                   # exactly what should be executed for the 
                                   # end user
```

In this way, `do-something-needing-cleanup-on-failure` will run only if the previous step succeeds, and `cleanup` will execute **only** if `do-something-needing-cleanup-on-failure` fails, without having to manage `job.status`. Am I missing something?

**Comment by jetexe** [comment]
In this case we need also add `run-post-on-cancelled-only` and `run-post-on-success-only` boolean flags, or (as I mention in my previews reply) a bitmask

**Comment by tarampampam** [comment]
@noirbizarre What do you think of the following example for running a cleanup command when do-something-needing-cleanup-on-failure fails?

```yaml
- run: do-something-needing-cleanup-on-failure # exit code 1

- if: failure()
  run: cleanup # I believe it will be executed only when the previous command fails immediately
```

Or could you give me a more detailed example of what you'd like to achieve?
