### ISSUE TITLE
Support for non standard shells

### ISSUE THREAD

**Issue by kr-sabre** [gacts/run-and-post-run#44]
Hi, I'm running mu github workflows with devenv in place.
For such the shell I provide to all of my steps is `devenv shell bash -- -e {0}`.

As per GitHub documentation any "non-standard" shell must contain `{0}` as a placeholder for the commands
When I try to provide it like this here, I'm getting `bash: {0}: No such file or directory` 

Any possibility it could be addressed?

**Comment by jetexe** [comment]
Hi! Thanks for your issue!

To run something from `devenv` shell, just omit `{0}` part.

Simple reproducible workflow example:

```yml
name: Example

on:
  push:

jobs:
  devenv:
    name: Development environment
    runs-on: ubuntu-latest
    container: nixos/nix:latest
    steps:
      - uses: actions/checkout@v4
      - run: nix-env --install --attr devenv -f https://github.com/NixOS/nixpkgs/tarball/nixpkgs-unstable
      - run: nix-env --install --attr nodejs -f https://github.com/NixOS/nixpkgs/tarball/nixpkgs-unstable
      - run: devenv init
      - run: devenv shell bash -- -e -c 'echo "Bash shell ready"'
      - name: Run this action
        uses: gacts/run-and-post-run@v1.4.2
        with:
          shell: devenv shell bash --
          run: echo "First"
              "(can be multiline)"
          post: |
            echo "First post"
            echo "(can run multiply commands)"
```
